add homework2
larechik/ValeriyaMakhnovets_LevelUp pull request #2
Opened 2020-10-06 16:42 UTC by larechik

2020-10-06 17:18 UTC, khda91 requested changes
Исправить комментарий

2020-10-06 17:18 UTC, khda91 commented on pom.xml
> +                    <target>7</target>
Почему java 7, а не 8?

2020-10-08 12:21 UTC, larechik commented on pom.xml
> +                    <target>7</target>
Потому что дефолтом так выставилось, а я не обратила внимание.

2020-10-08 12:26 UTC, larechik commented on pom.xml
> +                    <target>7</target>
Исправила и закоммитила изменения версии

2020-10-09 19:20 UTC, khda91 approved these changes
Работа принята. Можно мёржить в мастер

2020-10-11 16:01 UTC, merged